# Generated by Django 4.2 on 2023-04-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canname', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=122)),
            ],
        ),
    ]
